Tests function on Mac
rfjakob/cshatag pull request #20
Opened 2022-01-01 23:20 UTC by duncanbarth

I found that the tests for cshatag doesn't work in MacOS - but the tool itself will compile and function. 

I hacked in some conditionals to the test script so it will also run under MacOS. Its pretty ugly - and makes some assumptions that may not always be correct (the main one being that if set/getfattr exists we're on linux, otherwise if xattr exists assume we're on a Mac). It will however run all tests on a Mac without any packages outside of the xcode cli tools and go.

I'm totally open to suggestions for improvement here!

2022-01-05 17:41 UTC, rfjakob requested changes
Hi, thanks for the PR! Having the tests work on MacOS would be nice.

I suggest to introduce bash functions `set_sha256`, `set_ts`, `get_sha256`. They would use setfattr/getfattr if available, then xattr, then fail if neither is available.

A few more comments inline.

2022-01-05 17:41 UTC, rfjakob commented on tests/run_tests.sh
> +if [ "$ATTRVER" = "linux" ]
if [[ $(uname) == Darwin ]] ; then
diff -u 5.expected.mac 5.err
else
...
fi

2022-01-05 17:41 UTC, rfjakob commented on tests/run_tests.sh
> +fi
Just delete the "have gefattr / setfattr" check without replacement, it's not worth the hassle

2022-01-08 20:15 UTC, duncanbarth commented
I probably should have squashed those commits, but in any case, I've implemented your suggested changes.

2022-01-26 18:31 UTC, closed without merging

2022-01-26 18:31 UTC, rfjakob commented
Merged as 997c309, thanks!